### ISSUE TITLE
learn.inn.org wireframe

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#24]
- [x] Switch out orange section for an image
- [x] Create an option where the homepage has a background (image or pattern)
- [x] Update links (in general, can't be blue, must be something else)
- [x] Create options for resource boxes. For example 1. blue on hover and the whole box is a link 2. Article count as a button instead of a link... etc.

**Comment by gabehong** [comment]
new wireframes at https://www.dropbox.com/s/2w8zt4cd0t3tcl6/learn-homepage-wireframes-v2.pdf?dl=0

**Comment by julia67** [comment]
**Global:**
- [ ] Add very slight drop shadow to all blue buttons for readability
- [ ] Square corners on newsletter signup field 
- [ ] If buttons are caps, the donate button should be caps too
- [ ] Remove extraneous horizontal rules
- [ ] Headline hover color should stay #000
- [ ] Sign-up box should have same treatment on both sites (preferably the grey screen like the homepage)

**Learn:**
- [ ] Remove color overlay on photo
- [ ] Use no colors except blue (...although I like the red links – are those the brand crimson?)
- [ ] Top nav items should have the same baseline
- [ ] For hover state, just change the border color to blue instead of the full-color hover effect
- [ ] Add transparent white overlay behind modal

**Comment by gabehong** [comment]
new pdf at https://www.dropbox.com/s/mdwv397nfyslxph/learn-homepage-wireframes-v3.pdf?dl=0

**Comment by benlk** [comment]
v4: https://www.dropbox.com/s/wp8lyujmlss0641/learn-homepage-wireframes-v4.pdf?dl=0

- [ ] left logo, right-aligned menu in header. see largo.inn.org styles for how we did this: https://github.com/INN/umbrella-inndev/blob/master/wp-content/themes/largoproject/less/_nav.less
- [ ] Homepage layout:
    - [ ] search box, background image is configurable (probably just as theme option)
    - [ ] centered inline-block arrangement of category boxes, with square drop shadow
    - [ ] subscribe widget
- [ ] footer, in span4/span8 split, with the span8 containing:
    - [ ] a textwidget with large text
    - [ ] a menu arranged horizontally (how does this collapse)
    - [ ] common INN footer partial, replacing largo/partials/footer-boilerplate.php (probably part of INN's

**Comment by benlk** [comment]
This is the image used in the wireframe: https://unsplash.com/photos/PeUJyoylfe4

**Comment by benlk** [comment]
Some questions about the boxes area of the homepage:

<img width="1010" alt="screen shot 2017-07-14 at 4 35 27 pm" src="https://user-images.githubusercontent.com/1754187/28229857-7e04face-68b2-11e7-81e3-83cb287fbf5d.png">

- Is the whole box supposed to be a link, or just the title text and the interior text?
- How often will these be updated? Can they be hardcoded or should they be editable, like text widgets?
- We still are not doing the red text count, correct?

**Comment by kaylima** [comment]
- Is the whole box supposed to be a link, or just the title text and the interior text?
Whole box

- How often will these be updated? Can they be hardcoded or should they be editable, like text widgets?
They should be editable (the order and the text of each box).

- We still are not doing the red text count, correct?
Correct, no article count. Thanks!

**Comment by benlk** [comment]
Configuration options captured in #30.
