### ISSUE TITLE
QA Review - Desktop

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#27]
- [ ] Main image should be full-width
- [x] Remove “Don’t miss…”
- [x] Update Global nav to match mockup EXCEPT make sure to remove INNovation. Top left links should be “INN”, “INN Labs” and “Largo”.
- [x] Search input box and button should be shorter and wider
- [x] Add navigation and DONATE button to top right
- [x] Replace INN logo with Learn logo
- [x] Newsletter signup area: less wide and shorter with smaller font size
- [x] Newsletter input/button: also shorter - check mockup for button style
- [x] Footer should be the same as inn.org

**Comment by benlk** [comment]
## Configuration changes

>  Remove “Don’t miss…”

>  Update Global nav to match mockup EXCEPT make sure to remove INNovation. Top left links should be “INN”, “INN Labs” and “Largo”.

> Footer should be the same as inn.org

This inherits the styles from the `inn` theme, and I'll update the partials. The remaining differences are the configuration of the widget in the footer and the configuration of the "Footer Navigation" menu.

## Pain points

>  Main image should be full-width

Here's the page's layout:
```
body.home.blog
  div#page.hfeed.clearfix <- sets the width of the page
    div#main.row-fluid.clearfix
      div#content.stories.span12.CJETHomepageLayout
        section#home-search
```

Our options here are: 
1. completely rebuild the homepage's HTML so that the image's section is not constrained by div#page's width styles
2. extra-hacky CSS to position the 
3. remove the padding that exists on #page at all different viewport sizes, and re-add it to `.sticky-nav-wrapper`, `#main-nav`, `#secondary-nav`, the homepage sections #boxes and #email, and #footer-bg

**Comment by benlk** [comment]
Except the main image change, all of this is done. Do we want to continue with the main image, or nah?

**Comment by kaylima** [comment]
We're going to leave the main image as-is.
